version: "3.8"
services:
  app:
    image: gaurav4912/posbs-restaurant-backend:0.0.1-SNAPSHOT
    ports:
      - 8090:8090
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/restaurant_data?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_data
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"  # Exposing MySQL port
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data: {}












  #services:
#  mysql:
#    image: mysql:8.0.34
#    environment:
#      MYSQL_DATABASE: restaurant_spring
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#    ports:
#      - "3307:3306"
#    volumes:
#      - ./mysql-data:/var/lib/mysql
#
#  app:
#    image: gaurav4912/posbs-restaurant-backend:0.0.1-SNAPSHOT
#    depends_on:
#      - mysql
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/restaurant_data
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: Localhost123
#    ports:
#      - "8090:8090"

